"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "../../../../lib/supabase/client";
import ChatClient from "../../../components/ChatClient";
import {WorkspaceRailLinks} from "../../../components/WorkspaceIconRail";
import WorkspaceThemeScope from "../../../components/WorkspaceThemeScope";
import "../../../components/messages-shell.css";
import "./groups.css";
type Group={id:string;name:string;avatar_url:string|null;is_workspace_group:boolean};type Person={id:string;full_name:string|null;avatar_url:string|null};
const initials=(name:string)=>(name.split(" ").map(item=>item[0]).join("").slice(0,2)||"G").toUpperCase();
export default function GroupsPage(){
 const{workspaceId}=useParams<{workspaceId:string}>(),router=useRouter(),[meId,setMeId]=useState(""),[groups,setGroups]=useState<Group[]>([]),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState(""),[dialog,setDialog]=useState(false),[step,setStep]=useState<1|2>(1),[picked,setPicked]=useState<Set<string>>(new Set()),[name,setName]=useState(""),[status,setStatus]=useState("");
 const load=useCallback(async()=>{const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user){router.replace("/auth");return}setMeId(user.id);const[{data:allGroups},{data:membership},{data:rows}]=await Promise.all([c.from("channels").select("id,name,avatar_url,is_workspace_group").eq("workspace_id",workspaceId).eq("kind","group").order("created_at"),c.from("channel_members").select("channel_id").eq("user_id",user.id),c.from("workspace_members").select("user_id").eq("workspace_id",workspaceId)]),joined=new Set((membership||[]).map(item=>item.channel_id)),visible=((allGroups||[]) as Group[]).filter(item=>item.is_workspace_group||joined.has(item.id));setGroups(visible);setSelected(current=>current||visible[0]?.id||"");const ids=(rows||[]).map(row=>row.user_id).filter(id=>id!==user.id),{data:profiles}=ids.length?await c.from("workspace_profiles").select("id,full_name,avatar_url").eq("workspace_id",workspaceId).in("id",ids):{data:[]};setPeople((profiles||[]) as Person[])},[router,workspaceId]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{if(!name.trim()||!meId)return;setStatus("Creating group…");const c=createClient(),{data:channelId,error}=await c.rpc("create_workspace_group",{target_workspace_id:workspaceId,group_name:name.trim(),member_ids:[...picked]});if(error||!channelId){setStatus(`${error?.message||"Group could not be created."} Run create-workspace-group-migration.sql once if needed.`);return}setDialog(false);setName("");setPicked(new Set());setStep(1);await load();setSelected(String(channelId))};
 return <main className="groupsShell"><WorkspaceThemeScope workspaceId={workspaceId} userId={meId}/><aside className="messagesRail"><Link className="railBrand" href={`/workspace/${workspaceId}`} aria-label="Converge"><svg viewBox="0 0 64 58"><path d="M32 29C22 11 7 11 7 24c0 11 11 15 25 5"/><path d="M32 29C52 11 59 24 54 35c-4 9-16 6-22-6"/><path d="M32 29C29 53 14 52 13 39c0-11 11-14 19-10"/><circle cx="32" cy="29" r="4"/></svg></Link><WorkspaceRailLinks workspaceId={workspaceId} active="groups"/><div className="railSpacer"/><Link href="/dashboard" aria-label="All workspaces" title="All workspaces">⌘</Link></aside><aside className="groupsIndex"><header><div><small>YOUR WORKSPACE</small><h1>Groups</h1></div><button onClick={()=>setDialog(true)} aria-label="Create group">＋</button></header><p>Groups you belong to</p><div>{groups.map(group=><button className={selected===group.id?"active":""} onClick={()=>setSelected(group.id)} key={group.id}><i>{group.avatar_url?<img src={group.avatar_url} alt=""/>:initials(group.name)}</i><span><b>{group.name}</b><small>{group.is_workspace_group?"Every workspace member":"Private group"}</small></span></button>)}</div></aside><section className="groupsChat">{selected?<ChatClient workspaceId={workspaceId} chatId="group" requestedChannelId={selected}/>:<div className="groupWelcome"><h2>Your groups live here</h2><p>Create a group or choose one from the list to start chatting.</p></div>}</section>{dialog&&<div className="groupCreateBackdrop" onMouseDown={event=>event.target===event.currentTarget&&setDialog(false)}><section><header><span><small>NEW GROUP · STEP {step} OF 2</small><h2>{step===1?"Choose members":"Name your group"}</h2></span><button onClick={()=>setDialog(false)}>×</button></header>{step===1?<><div className="groupPicker">{people.map(person=><button className={picked.has(person.id)?"picked":""} onClick={()=>setPicked(current=>{const next=new Set(current);if(next.has(person.id))next.delete(person.id);else next.add(person.id);return next})} key={person.id}><i>{person.avatar_url?<img src={person.avatar_url} alt=""/>:initials(person.full_name||"Member")}</i><span>{person.full_name||"Member"}</span><em>{picked.has(person.id)?"✓":"＋"}</em></button>)}</div><button className="groupNext" disabled={!picked.size} onClick={()=>setStep(2)}>Next · {picked.size} selected</button></>:<><label>Group name<input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Design team"/></label><button className="groupNext" disabled={!name.trim()} onClick={()=>void create()}>Create group</button><button className="groupBack" onClick={()=>setStep(1)}>Back to members</button></>}{status&&<p className="groupCreateStatus">{status}</p>}</section></div>}</main>;
}
