"use client";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "../../../lib/supabase/client";
import ProfilePostCard,{ProfileFeedPost} from "../../components/ProfilePostCard";
import WorkspaceThemeScope from "../../components/WorkspaceThemeScope";
import "../profile-feed-posts.css";
import "./visitor-profile.css";
import "./visitor-bio.css";
type Profile={id:string;full_name:string|null;avatar_url:string|null;job_title:string|null;bio?:string|null};
const initials=(name:string)=>(name.split(" ").map(x=>x[0]).join("").slice(0,2)||"U").toUpperCase();
export default function VisitorProfile(){
 const{userId}=useParams<{userId:string}>(),router=useRouter(),[workspaceId,setWorkspaceId]=useState(""),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Profile|null>(null),[posts,setPosts]=useState<ProfileFeedPost[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){router.replace("/auth");return}const space=new URLSearchParams(window.location.search).get("workspace");if(!space){router.replace("/dashboard");return}if(user.id===userId){router.replace(`/profile?workspace=${space}`);return}setWorkspaceId(space);const[{data:membership},{data:profileRows},{data:mine},{data:rows}]=await Promise.all([s.from("workspace_members").select("user_id").eq("workspace_id",space).eq("user_id",user.id).maybeSingle(),s.rpc("get_workspace_chat_identities",{target_workspace_id:space}),s.from("workspace_profiles").select("id,full_name,avatar_url,job_title,bio").eq("workspace_id",space).eq("id",user.id).maybeSingle(),s.from("posts").select("id,workspace_id,author_id,body,created_at,archived_at,post_type,attachment_url,attachment_name,poll_options").eq("author_id",userId).eq("workspace_id",space).is("archived_at",null).order("created_at",{ascending:false}) ]);let p=((profileRows as Profile[]|null)||[]).find(item=>item.id===userId)||null;if(!p){const{data:fallbackProfile}=await s.from("workspace_profiles").select("id,full_name,avatar_url,job_title,bio").eq("workspace_id",space).eq("id",userId).maybeSingle();p=fallbackProfile as Profile|null}if(!membership){setError("This workspace is unavailable.");setLoading(false);return}setProfile(p as Profile|null);setMe((mine||{id:user.id,full_name:user.email?.split("@")[0]||"Member",avatar_url:null,job_title:null,bio:null})as Profile);const raw=rows||[];if(!raw.length){setPosts([]);setLoading(false);return}const ids=raw.map(x=>x.id),[{data:likes},{data:comments},{data:shares},{data:saves},{data:votes}]=await Promise.all([s.from("post_likes").select("post_id,user_id").in("post_id",ids),s.from("post_comments").select("post_id").in("post_id",ids),s.from("post_shares").select("post_id").in("post_id",ids),s.from("post_saves").select("post_id,user_id").in("post_id",ids),s.from("poll_votes").select("post_id,user_id,option_index").in("post_id",ids)]);setPosts(raw.map(x=>({...x,post_type:x.post_type||"update",attachment_url:x.attachment_url||null,attachment_name:x.attachment_name||null,poll_options:x.poll_options||null,author:(p||{id:userId,full_name:"Member",avatar_url:null,job_title:null})as Profile,likes:(likes||[]).filter(v=>v.post_id===x.id).length,liked:(likes||[]).some(v=>v.post_id===x.id&&v.user_id===user.id),comments:(comments||[]).filter(v=>v.post_id===x.id).length,shares:(shares||[]).filter(v=>v.post_id===x.id).length,saves:(saves||[]).filter(v=>v.post_id===x.id).length,saved:(saves||[]).some(v=>v.post_id===x.id&&v.user_id===user.id),votes:((x.poll_options as string[]||[])).map((_,index)=>(votes||[]).filter(v=>v.post_id===x.id&&v.option_index===index).length),voted:(votes||[]).find(v=>v.post_id===x.id&&v.user_id===user.id)?.option_index??null}))as ProfileFeedPost[]);setLoading(false)},[router,userId]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0),client=createClient(),channel=client.channel(`visitor-profile:${userId}`).on("postgres_changes",{event:"*",schema:"public",table:"posts"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"post_likes"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"post_comments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"post_saves"},()=>void load()).subscribe();return()=>{window.clearTimeout(timer);void client.removeChannel(channel)}},[load,userId]);
 if(loading)return <main className="visitorProfile loading">Loading profile…</main>;if(!profile||!me)return <main className="visitorProfile loading">{error||"This profile is unavailable."}</main>;
 return <main className="visitorProfile"><WorkspaceThemeScope workspaceId={workspaceId}/><header className="visitorTop"><Link href={`/workspace/${workspaceId}`}>← Workspace</Link><Link className="visitorMessage" href={`/workspace/${workspaceId}/messages/${profile.id}`}>Message</Link></header><section className="visitorHero">{profile.avatar_url?<img src={profile.avatar_url} alt={profile.full_name||"Member"}/>:<span>{initials(profile.full_name||"Member")}</span>}<div><small>MEMBER PROFILE</small><h1>{profile.full_name||"Member"}</h1><b>{profile.job_title||"Workspace member"}</b><p className="visitorBio">{profile.bio||"No bio added yet"}</p><div className="visitorStats"><strong>{posts.length}<em>Posts</em></strong></div></div></section><section className="visitorPosts"><header><p>POSTS</p><span>{posts.length} shared</span></header>{posts.length?<div className="visitorFeed">{posts.map(post=><ProfilePostCard key={post.id} post={post} me={me} refresh={load}/>)}</div>:<div className="visitorEmpty"><b>No posts yet</b><span>When {profile.full_name||"this member"} shares something, it will appear here.</span></div>}</section></main>;
}
