"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {createClient} from "../../lib/supabase/client";
import PhotoPreview from "./PhotoPreview";
import "./contact-info.css";

export type ContactView="main"|"search"|"media"|"starred"|"notifications";
type Message={id:string;body:string;message_type:string;created_at:string;attachment_url:string|null;attachment_name:string|null;post_id:string|null;deleted_at?:string|null};
type Props={workspaceId:string;meId:string;person:{id:string;full_name:string|null;avatar_url:string|null;job_title:string|null;bio?:string|null};messages:Message[];starred:Set<string>;initialView:ContactView;muted:boolean;blocked:boolean;notice?:string;onClose:()=>void;onJump:(id:string)=>void;onAction:(action:string)=>void};
export default function ContactInfoSheet(p:Props){
 const [view,setView]=useState<ContactView>(p.initialView),[query,setQuery]=useState(""),[photo,setPhoto]=useState(false),[tab,setTab]=useState("media"),[common,setCommon]=useState<{id:string;name:string;avatar_url:string|null}[]>([]),[groupPhoto,setGroupPhoto]=useState<{src:string|null;name:string}|null>(null);
 const panel=useRef<HTMLElement>(null);const closeRef=useRef(p.onClose);closeRef.current=p.onClose;const name=p.person.full_name||"Member";const self=p.person.id===p.meId;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;panel.current?.focus();const key=(e:KeyboardEvent)=>{if(document.querySelector(".chatPhotoBackdrop"))return;if(e.key==="Escape")closeRef.current();if(e.key==="Tab"){const controls=[...(panel.current?.querySelectorAll<HTMLElement>("button:not(:disabled),a,input")||[])].filter(el=>el.getClientRects().length);const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus()}},[]);
 useEffect(()=>{let alive=true;void(async()=>{const c=createClient();const [{data:a},{data:b}]=await Promise.all([c.from("channel_members").select("channel_id").eq("user_id",p.meId).is("left_at",null),c.from("channel_members").select("channel_id").eq("user_id",p.person.id).is("left_at",null)]);const other=new Set((b||[]).map(r=>r.channel_id));const ids=(a||[]).filter(r=>other.has(r.channel_id)).map(r=>r.channel_id);if(!ids.length)return;const{data}=await c.from("channels").select("id,name,avatar_url").eq("kind","group").eq("workspace_id",p.workspaceId).in("id",ids);if(alive)setCommon(data||[])})();return()=>{alive=false}},[p.meId,p.person.id,p.workspaceId]);
 const messages=p.messages.filter(m=>!m.deleted_at&&m.message_type!=="system");const shared=messages.filter(m=>m.attachment_url||m.post_id||/https?:\/\//.test(m.body));
 const rows=view==="starred"?messages.filter(m=>p.starred.has(m.id)):view==="media"?shared.filter(m=>tab==="media"?m.message_type==="media":tab==="docs"?m.message_type==="file"||m.message_type==="voice":!!m.post_id||/https?:\/\//.test(m.body)):messages.filter(m=>(m.body+" "+(m.attachment_name||"")).toLowerCase().includes(query.toLowerCase()));
 const row=(icon:string,label:string,action:()=>void,detail?:string,danger=false)=><button className={danger?"danger":""} onClick={action}><i>{icon}</i><span>{label}{detail&&<small>{detail}</small>}</span><b>›</b></button>;
 return createPortal(<div className="contactBackdrop" onMouseDown={e=>e.target===e.currentTarget&&p.onClose()}><aside ref={panel} tabIndex={-1} className="contactSheet" role="dialog" aria-modal="true" aria-label={view==="main"?"Contact info":view}><header><button aria-label={view==="main"?"Close contact info":"Back"} onClick={()=>view==="main"||view===p.initialView?p.onClose():setView("main")}>{view==="main"?"×":"←"}</button><h2>{({main:"Contact info",search:"Search messages",media:"Media, links and docs",starred:"Starred messages",notifications:"Notification settings"})[view]}</h2></header><div className="contactScroll">{p.notice&&<p className="contactStatus" role="status">{p.notice}</p>}
 {view==="main"?<><div className="contactHero"><button className="contactPhoto" aria-label="View contact photo" onClick={()=>setPhoto(true)}>{p.person.avatar_url?<img src={p.person.avatar_url} alt=""/>:<span>{name.slice(0,1)}</span>}</button><h1>{name}{self&&<small> (You)</small>}</h1><p>{p.person.job_title||"Workspace member"}</p><Link href={`/profile/${p.person.id}?workspace=${p.workspaceId}`}>{self?"Open your profile":"View profile"} ↗</Link>{!self&&<div className="contactQuick"><button disabled={p.blocked} aria-label="Voice call"><svg viewBox="0 0 24 24"><path d="M7 3H3v3c0 8.3 6.7 15 15 15h3v-4l-5-2-2 2a15 15 0 0 1-7-7l2-2Z"/></svg><small>Voice</small></button><button disabled={p.blocked} aria-label="Video call"><svg viewBox="0 0 24 24"><rect x="2" y="5" width="14" height="14" rx="2"/><path d="m16 10 6-4v12l-6-4Z"/></svg><small>Video</small></button><button onClick={()=>setView("search")}><svg viewBox="0 0 24 24"><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></svg><small>Search</small></button></div>}</div>
 <section className="contactSection"><small>BIO</small><p>{p.person.bio?.trim()||"This member has not added a bio yet."}</p></section>
 <section className="contactRows">{row("▧","Media, links and docs",()=>setView("media"),`${shared.length} shared items`)}<div className="contactThumbnails">{shared.filter(m=>m.message_type==="media"&&m.attachment_url&&!/\.(mp4|webm|mov)$/i.test(m.attachment_name||"")).slice(0,4).map(m=><button key={m.id} onClick={()=>p.onJump(m.id)}><img loading="lazy" src={m.attachment_url!} alt={m.attachment_name||"Shared image"}/></button>)}</div>{row("☆","Starred messages",()=>setView("starred"),`${messages.filter(m=>p.starred.has(m.id)).length} messages`)}{!self&&row("♧","Notification settings",()=>setView("notifications"),p.muted?"Muted on this device":"On")}{!self&&row("◷","Disappearing messages",()=>p.onAction("disappearing"),"Manage local history visibility")}</section>
 {!self&&<section className="contactRows"><small>{common.length} GROUPS IN COMMON</small>{common.map(g=><div className="commonGroupRow" key={g.id}><button className="commonGroupPhoto" aria-label={`View ${g.name} group photo`} onClick={()=>setGroupPhoto({src:g.avatar_url,name:g.name})}>{g.avatar_url?<img src={g.avatar_url} alt="" loading="lazy"/>:<i>{g.name.slice(0,1)}</i>}</button><Link href={`/workspace/${p.workspaceId}/messages/group?channel=${g.id}`} onClick={p.onClose}><span><b>{g.name}</b><small>Group in common</small></span><i>›</i></Link></div>)}</section>}
 <section className={`contactRows ${self?"selfChatActions":""}`}>{!self&&row("♡","Add to favourites",()=>p.onAction("favourite"))}{!self&&row("▣","Add to list",()=>p.onAction("list"))}{row("↓","Export chat",()=>p.onAction("export"))}{row("⊖","Clear chat",()=>p.onAction("clear"),"Only your history on this device",true)}{!self&&row("⊘",`${p.blocked?"Unblock":"Block"} ${name}`,()=>p.onAction("block"),undefined,true)}{!self&&row("⚑",`Report ${name}`,()=>p.onAction("report"),undefined,true)}{row("⌫","Delete chat",()=>p.onAction("delete"),"Remove from your inbox on this device",true)}</section></>:view==="notifications"?<div className="contactSection"><h3>Message notifications</h3><p>Mute popup messages and sounds from this conversation on this device. Incoming calls are separate.</p><button className="contactPrimary" onClick={()=>p.onAction("mute")}>{p.muted?"Unmute":"Mute"} notifications</button></div>:<><div className="contactSearch">{view==="search"&&<input autoFocus aria-label="Search messages" placeholder="Search this conversation" value={query} onChange={e=>setQuery(e.target.value)}/>} {view==="media"&&<div>{["media","links","docs"].map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>}</div>{rows.length?rows.map(m=><button className="contactResult" key={m.id} onClick={()=>p.onJump(m.id)}><b>{m.attachment_name||m.body||"Shared post"}</b><small>{new Date(m.created_at).toLocaleString()}</small></button>):<p className="contactNoResults">No {view==="search"?"matching messages":view==="starred"?"starred messages":"shared items"}.</p>}</>}
 </div></aside>{groupPhoto&&<PhotoPreview {...groupPhoto} onClose={()=>setGroupPhoto(null)}/>}{photo&&<PhotoPreview src={p.person.avatar_url} name={name} onClose={()=>setPhoto(false)}/>}</div>,document.body);
}
