"use client";
import {createClient} from "../../lib/supabase/client";
import {callDuration,startRingtone} from "./ringtone";
import {attachRemoteTrack,getIceServers} from "./webrtc-config";
import "./group-call.css";

type Mode="audio"|"video";
type Signal={type:"ring"|"join"|"reject"|"offer"|"answer"|"ice"|"leave";from:string;to?:string;workspaceId:string;channelId:string;callId:string;mode?:Mode;payload?:RTCSessionDescriptionInit|RTCIceCandidateInit;name?:string;groupName?:string};
type Pending={callerId:string;mode:Mode;channelId:string;callId:string;groupName?:string};

export function attachGroupCallRuntime({workspaceId,channelId,meId}:{workspaceId:string;channelId:string;meId:string}){
 const client=createClient(),room=client.channel(`group-call:${workspaceId}`,{config:{private:true}}),peers=new Map<string,RTCPeerConnection>(),names=new Map<string,string>(),pendingIce=new Map<string,RTCIceCandidateInit[]>();
 let stream:MediaStream|null=null,overlay:HTMLDivElement|null=null,mode:Mode="audio",myName="Member",groupName="Group",callId="",active=false,initiated=false,connected=false,startedAt=0,peakMembers=1,summarySent=false,ringingFrom="",stopRing:(()=>void)|null=null,soloTimer:ReturnType<typeof setTimeout>|null=null;
 void Promise.all([client.from("workspace_profiles").select("full_name").eq("workspace_id",workspaceId).eq("id",meId).maybeSingle(),client.from("channels").select("name").eq("workspace_id",workspaceId).eq("id",channelId).maybeSingle()]).then(([person,group])=>{myName=person.data?.full_name||"Member";groupName=group.data?.name||"Group"});
 const send=(signal:Omit<Signal,"workspaceId"|"channelId"|"callId">)=>callId?room.send({type:"broadcast",event:"signal",payload:{...signal,workspaceId,channelId,callId} satisfies Signal}):Promise.resolve("skipped");
 const initials=(name:string)=>name.trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()||"M";
 const updateCount=()=>{const count=overlay?.querySelector(".groupCallCount");if(count)count.textContent=`${peers.size+1} participant${peers.size?"s":""}`};
 const tile=(id:string,name:string,mine=false)=>{if(!overlay)return null;let box=overlay.querySelector<HTMLElement>(`[data-person="${CSS.escape(id)}"]`);if(!box){box=document.createElement("article");box.dataset.person=id;box.className=mine?"isLocal":"isRemote";box.innerHTML='<video autoplay playsinline></video><i></i><b></b>';const video=box.querySelector("video")!;video.muted=mine;box.querySelector("i")!.textContent=initials(name);box.querySelector("b")!.textContent=`${name}${mine?" (You)":""}`;overlay.querySelector(".groupCallGrid")?.append(box);updateCount()}return box.querySelector("video") as HTMLVideoElement};
 const show=(incoming=false,callerId="",callerName="")=>{overlay?.remove();overlay=document.createElement("div");overlay.className=`groupCallOverlay ${incoming?"incoming":"active"} ${mode}Call`;overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");overlay.innerHTML=`<section><header><p>CONVERGE · ${incoming?"INCOMING":"LIVE"} ${mode.toUpperCase()} CALL</p><h2></h2><span class="groupCallCount"></span></header><div class="groupCallGrid"></div><footer>${incoming?'<button class="accept">Answer</button><button class="reject">Decline</button>':'<button class="mute" aria-pressed="false">Mute</button><button class="camera" aria-pressed="false">Camera off</button><button class="leave">End call</button>'}</footer></section>`;overlay.querySelector("h2")!.textContent=incoming?`${callerName||"A teammate"} · ${groupName}`:groupName;document.body.append(overlay);updateCount();if(incoming){overlay.querySelector(".accept")?.addEventListener("click",()=>void accept(callerId));overlay.querySelector(".reject")?.addEventListener("click",()=>{void send({type:"reject",from:meId,to:callerId,name:myName});close(false)})}else bindControls()};
 const media=async(next:Mode)=>{mode=next;stream=await navigator.mediaDevices.getUserMedia({audio:true,video:next==="video"});const local=tile(meId,myName,true);if(local){local.srcObject=stream;void local.play().catch(()=>{})}};
 const scheduleSoloEnd=()=>{if(soloTimer)clearTimeout(soloTimer);soloTimer=setTimeout(()=>{if(active&&connected&&peers.size===0)close(true)},900)};
 const removePeer=(id:string)=>{peers.delete(id);names.delete(id);pendingIce.delete(id);overlay?.querySelector(`[data-person="${CSS.escape(id)}"]`)?.remove();updateCount()};
 const peerFor=(id:string,name="Member")=>{const old=peers.get(id);if(old)return old;if(soloTimer){clearTimeout(soloTimer);soloTimer=null}names.set(id,name);const peer=new RTCPeerConnection({iceServers:getIceServers()}),remoteStream=new MediaStream();peers.set(id,peer);stream?.getTracks().forEach(track=>peer.addTrack(track,stream!));peer.onicecandidate=event=>{if(event.candidate)void send({type:"ice",from:meId,to:id,payload:event.candidate.toJSON(),name:myName})};peer.ontrack=event=>{const remote=tile(id,names.get(id)||name);if(remote){attachRemoteTrack(remoteStream,event);remote.srcObject=remoteStream;remote.muted=false;remote.volume=1;void remote.play().catch(()=>{})}};peer.onconnectionstatechange=()=>{if(peer.connectionState==="connected"){connected=true;if(!startedAt)startedAt=Date.now();peakMembers=Math.max(peakMembers,peers.size+1);updateCount()}else if(["failed","closed","disconnected"].includes(peer.connectionState)){removePeer(id);scheduleSoloEnd()}};return peer};
 const offer=async(id:string,name:string)=>{const peer=peerFor(id,name),description=await peer.createOffer();await peer.setLocalDescription(description);await send({type:"offer",from:meId,to:id,mode,payload:description,name:myName})};
 const accept=async(_callerId:string)=>{try{stopRing?.();stopRing=null;ringingFrom="";show();await media(mode);active=true;await send({type:"join",from:meId,mode,name:myName})}catch{close(false);alert("Microphone or camera permission is required.")}};
 const start=async(next:Mode)=>{try{mode=next;callId=crypto.randomUUID();initiated=true;connected=false;peakMembers=1;summarySent=false;show();await media(next);active=true;await send({type:"ring",from:meId,mode:next,name:myName,groupName})}catch{close(false);alert("Microphone or camera permission is required.")}};
 const saveSummary=async()=>{if(!initiated||summarySent||!callId)return;summarySent=true;const result=connected&&startedAt?callDuration(Date.now()-startedAt):"No answer";const{error}=await client.from("channel_messages").insert({workspace_id:workspaceId,channel_id:channelId,sender_id:meId,body:`Group ${mode==="video"?"video":"voice"} call • ${result} • ${peakMembers} participant${peakMembers===1?"":"s"}`,message_type:"text"});if(!error){window.dispatchEvent(new Event("converge:call-log"));window.dispatchEvent(new Event("converge:unread-chats"))}};
 const close=(notify=true)=>{if(soloTimer)clearTimeout(soloTimer);soloTimer=null;if(notify&&active)void send({type:"leave",from:meId,name:myName});stopRing?.();stopRing=null;ringingFrom="";void saveSummary();active=false;peers.forEach(peer=>peer.close());peers.clear();names.clear();pendingIce.clear();stream?.getTracks().forEach(track=>track.stop());stream=null;overlay?.remove();overlay=null;callId=""};
 const bindControls=()=>{overlay?.querySelector(".leave")?.addEventListener("click",()=>close());const camera=overlay?.querySelector<HTMLButtonElement>(".camera");if(camera)camera.hidden=mode!=="video";overlay?.querySelector(".mute")?.addEventListener("click",event=>{const track=stream?.getAudioTracks()[0];if(track){track.enabled=!track.enabled;const button=event.currentTarget as HTMLButtonElement;button.textContent=track.enabled?"Mute":"Unmute";button.setAttribute("aria-pressed",String(!track.enabled))}});camera?.addEventListener("click",event=>{const track=stream?.getVideoTracks()[0];if(track){track.enabled=!track.enabled;const button=event.currentTarget as HTMLButtonElement;button.textContent=track.enabled?"Camera off":"Camera on";button.setAttribute("aria-pressed",String(!track.enabled))}})};
 const addPendingIce=async(signal:Signal)=>{const peer=peers.get(signal.from),candidate=signal.payload as RTCIceCandidateInit;if(peer?.remoteDescription)await peer.addIceCandidate(candidate);else pendingIce.set(signal.from,[...(pendingIce.get(signal.from)||[]),candidate])};
 const flushIce=async(id:string,peer:RTCPeerConnection)=>{for(const candidate of pendingIce.get(id)||[])await peer.addIceCandidate(candidate);pendingIce.delete(id)};
 const receive=async(signal:Signal)=>{if(!signal||signal.from===meId||signal.workspaceId!==workspaceId||signal.channelId!==channelId||(signal.to&&signal.to!==meId))return;if(callId&&signal.callId!==callId)return;if(signal.type==="ring"&&!active){callId=signal.callId;mode=signal.mode||"audio";groupName=signal.groupName||groupName;ringingFrom=signal.from;show(true,signal.from,signal.name);stopRing?.();stopRing=startRingtone()}if(signal.type==="join"&&active){peakMembers=Math.max(peakMembers,peers.size+2);await offer(signal.from,signal.name||"Member")}if(signal.type==="offer"){const peer=peerFor(signal.from,signal.name);await peer.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flushIce(signal.from,peer);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await send({type:"answer",from:meId,to:signal.from,payload:answer,name:myName})}if(signal.type==="answer"){const peer=peers.get(signal.from);if(peer&&!peer.remoteDescription){await peer.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flushIce(signal.from,peer)}}if(signal.type==="ice"&&signal.payload)await addPendingIce(signal);if(signal.type==="leave"){if(!active&&ringingFrom===signal.from){close(false);return}peers.get(signal.from)?.close();removePeer(signal.from);scheduleSoloEnd()}};
 room.on("broadcast",{event:"signal"},({payload})=>void receive(payload as Signal)).subscribe(status=>{if(status!=="SUBSCRIBED")return;const key=`converge:auto-answer:${workspaceId}:group:${channelId}`,saved=sessionStorage.getItem(key);if(!saved)return;sessionStorage.removeItem(key);try{const pending=JSON.parse(saved) as Pending;if(pending.channelId!==channelId)return;mode=pending.mode;callId=pending.callId;groupName=pending.groupName||groupName;setTimeout(()=>void accept(pending.callerId),80)}catch{}});
 const click=(event:MouseEvent)=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>("button");if(!button)return;const requested=button.dataset.groupCall||button.getAttribute("aria-label")||button.textContent||"",kind=requested.toLowerCase(),headerCall=kind==="voice call"||kind==="video call",infoCall=!!button.closest(".groupHero")&&(kind.includes("voice")||kind.includes("video"));if(!headerCall&&!infoCall)return;event.preventDefault();event.stopPropagation();if(infoCall)document.querySelector<HTMLButtonElement>(".groupInfoSheet>header button")?.click();void start(kind.includes("video")?"video":"audio")};
 document.addEventListener("click",click);return()=>{document.removeEventListener("click",click);close(false);void client.removeChannel(room)};
}
