"use client";

import { createClient } from "../../lib/supabase/client";
import { callDuration, startRingtone } from "./ringtone";
import "./group-call.css";

type Mode = "audio" | "video";
type Signal = { type: "ring"|"join"|"reject"|"offer"|"answer"|"ice"|"leave"; from:string; to?:string; mode?:Mode; payload?:RTCSessionDescriptionInit|RTCIceCandidateInit; name?:string };
const iceServers: RTCIceServer[] = [{ urls:"stun:stun.l.google.com:19302" },{ urls:"stun:stun1.l.google.com:19302" }];

export function attachGroupCallRuntime({workspaceId,meId}:{workspaceId:string;meId:string}){
  const client=createClient(); const room=client.channel(`group-call:${workspaceId}`,{config:{private:true}}); const peers=new Map<string,RTCPeerConnection>(); let stream:MediaStream|null=null; let overlay:HTMLDivElement|null=null; let mode:Mode="audio"; let myName="Member"; let active=false;let initiated=false;let connected=false;let startedAt=0;let peakMembers=1;let summarySent=false;let ringingFrom="";let stopRing:(()=>void)|null=null;let soloTimer:ReturnType<typeof setTimeout>|null=null;
  void client.from("workspace_profiles").select("full_name").eq("workspace_id",workspaceId).eq("id",meId).maybeSingle().then(({data})=>{myName=data?.full_name||"Member"});
  const send=(signal:Signal)=>room.send({type:"broadcast",event:"signal",payload:signal});
  const tile=(id:string,name:string,mine=false)=>{if(!overlay)return null;let box=overlay.querySelector<HTMLElement>(`[data-person="${id}"]`);if(!box){box=document.createElement("article");box.dataset.person=id;box.innerHTML=`<video autoplay playsinline ${mine?"muted":""}></video><i>${name.slice(0,1).toUpperCase()}</i><b>${name}${mine?" (You)":""}</b>`;overlay.querySelector(".groupCallGrid")?.append(box)}return box.querySelector("video") as HTMLVideoElement};
  const show=(label:string,incoming=false,callerId="")=>{overlay?.remove();overlay=document.createElement("div");overlay.className=`groupCallOverlay ${incoming?"incoming":"active"} ${mode}Call`;overlay.innerHTML=`<section><header><p>${incoming?"Incoming":"Live"} group ${mode} call</p><h2>${label}</h2></header><div class="groupCallGrid"></div><footer>${incoming?'<button class="accept">Answer</button><button class="reject">Reject</button>':'<button class="mute">Mute</button><button class="camera">Camera</button><button class="leave">Leave</button>'}</footer></section>`;document.body.append(overlay);if(incoming){overlay.querySelector(".accept")?.addEventListener("click",()=>accept(callerId));overlay.querySelector(".reject")?.addEventListener("click",()=>{send({type:"reject",from:meId,to:callerId,name:myName});close(false)})}else bindControls()};
  const media=async(next:Mode)=>{mode=next;stream=await navigator.mediaDevices.getUserMedia({audio:true,video:next==="video"});const local=tile(meId,myName,true);if(local)local.srcObject=stream};
  const scheduleSoloEnd=()=>{if(soloTimer)clearTimeout(soloTimer);soloTimer=setTimeout(()=>{if(active&&connected&&peers.size===0)close(true)},800)};
  const peerFor=(id:string,name="Member")=>{const old=peers.get(id);if(old)return old;if(soloTimer){clearTimeout(soloTimer);soloTimer=null}const peer=new RTCPeerConnection({iceServers});peers.set(id,peer);stream?.getTracks().forEach(track=>peer.addTrack(track,stream!));peer.onicecandidate=e=>{if(e.candidate)send({type:"ice",from:meId,to:id,payload:e.candidate.toJSON(),name:myName})};peer.ontrack=e=>{const remote=tile(id,name);if(remote)remote.srcObject=e.streams[0]};peer.onconnectionstatechange=()=>{if(peer.connectionState==="connected"){connected=true;if(!startedAt)startedAt=Date.now();peakMembers=Math.max(peakMembers,peers.size+1)}else if(["failed","closed","disconnected"].includes(peer.connectionState)){peers.delete(id);overlay?.querySelector(`[data-person="${id}"]`)?.remove();scheduleSoloEnd()}};return peer};
  const offer=async(id:string,name:string)=>{const peer=peerFor(id,name);const description=await peer.createOffer();await peer.setLocalDescription(description);send({type:"offer",from:meId,to:id,mode,payload:description,name:myName})};
  const accept=async(callerId:string)=>{try{stopRing?.();stopRing=null;ringingFrom="";overlay?.remove();show(myName);await media(mode);active=true;send({type:"join",from:meId,to:callerId,mode,name:myName})}catch{close(false);alert("Microphone or camera permission is required.")}};
  const start=async(next:Mode)=>{try{mode=next;show(myName);await media(next);active=true;initiated=true;connected=false;peakMembers=1;summarySent=false;send({type:"ring",from:meId,mode:next,name:myName})}catch{close(false);alert("Microphone or camera permission is required.")}};
  const saveSummary=async()=>{if(!initiated||summarySent)return;summarySent=true;const result=connected?callDuration(Date.now()-startedAt):"No answer";const{data:channel}=await client.from("channels").select("id").eq("workspace_id",workspaceId).eq("kind","group").order("created_at",{ascending:true}).limit(1).maybeSingle();if(channel)await client.from("channel_messages").insert({workspace_id:workspaceId,channel_id:channel.id,sender_id:meId,body:`Group ${mode==="video"?"video":"voice"} call • ${result} • ${peakMembers} member${peakMembers===1?"":"s"} joined`,message_type:"text"})};
  const close=(notify=true)=>{if(soloTimer)clearTimeout(soloTimer);soloTimer=null;if(notify&&active)send({type:"leave",from:meId,name:myName});stopRing?.();stopRing=null;ringingFrom="";void saveSummary();active=false;peers.forEach(p=>p.close());peers.clear();stream?.getTracks().forEach(t=>t.stop());stream=null;overlay?.remove();overlay=null};
  const bindControls=()=>{overlay?.querySelector(".leave")?.addEventListener("click",()=>close());overlay?.querySelector(".mute")?.addEventListener("click",e=>{const track=stream?.getAudioTracks()[0];if(track){track.enabled=!track.enabled;(e.currentTarget as HTMLButtonElement).textContent=track.enabled?"Mute":"Unmute"}});overlay?.querySelector(".camera")?.addEventListener("click",e=>{const track=stream?.getVideoTracks()[0];if(track){track.enabled=!track.enabled;(e.currentTarget as HTMLButtonElement).textContent=track.enabled?"Camera off":"Camera on"}})};
  const receive=async(signal:Signal)=>{if(!signal||signal.from===meId||(signal.to&&signal.to!==meId))return;if(signal.type==="ring"&&!active){mode=signal.mode||"audio";ringingFrom=signal.from;show(signal.name||"Member",true,signal.from);stopRing?.();stopRing=startRingtone()}if(signal.type==="join"&&active){if(initiated&&!connected){connected=true;startedAt=Date.now()}peakMembers=Math.max(peakMembers,peers.size+2);await offer(signal.from,signal.name||"Member")}if(signal.type==="offer"){const peer=peerFor(signal.from,signal.name);await peer.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);send({type:"answer",from:meId,to:signal.from,payload:answer,name:myName})}if(signal.type==="answer")await peers.get(signal.from)?.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);if(signal.type==="ice"&&signal.payload)await peers.get(signal.from)?.addIceCandidate(signal.payload as RTCIceCandidateInit);if(signal.type==="leave"){if(!active&&ringingFrom===signal.from){close(false);return}peers.get(signal.from)?.close();peers.delete(signal.from);overlay?.querySelector(`[data-person="${signal.from}"]`)?.remove();scheduleSoloEnd()}};
  room.on("broadcast",{event:"signal"},({payload})=>void receive(payload as Signal)).subscribe(status=>{if(status!=="SUBSCRIBED")return;const key=`converge:auto-answer:${workspaceId}:group`;const saved=sessionStorage.getItem(key);if(!saved)return;sessionStorage.removeItem(key);try{const pending=JSON.parse(saved) as {callerId:string;mode:Mode};mode=pending.mode;window.setTimeout(()=>void accept(pending.callerId),80)}catch{}});
  const click=(e:MouseEvent)=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>("button");if(!button)return;const requested=button.dataset.groupCall||button.getAttribute("aria-label")||button.textContent||"";const callKind=requested.toLowerCase();const headerCall=callKind==="voice call"||callKind==="video call";const infoCall=!!button.closest(".groupHero")&&(callKind.includes("voice")||callKind.includes("video"));if(!headerCall&&!infoCall)return;e.preventDefault();e.stopPropagation();if(infoCall)document.querySelector<HTMLButtonElement>(".groupInfoSheet>header button")?.click();void start(callKind.includes("video")?"video":"audio")};document.addEventListener("click",click);
  return()=>{document.removeEventListener("click",click);close(false);client.removeChannel(room)};
}
