"use client";
import {FormEvent,useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {createClient} from "../../lib/supabase/client";

const localDateTime=(offsetMinutes:number)=>{const value=new Date(Date.now()+offsetMinutes*60000),shifted=new Date(value.getTime()-value.getTimezoneOffset()*60000);return shifted.toISOString().slice(0,16)};

export default function MeetingReminderComposer({workspaceId,meId}:{workspaceId:string;meId:string}){
 const[host,setHost]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[title,setTitle]=useState("Workspace meeting"),[starts,setStarts]=useState(()=>localDateTime(60)),[duration,setDuration]=useState(60),[details,setDetails]=useState(""),[name,setName]=useState("Workspace member"),[busy,setBusy]=useState(false),[status,setStatus]=useState("");
 useEffect(()=>{const find=()=>setHost(document.querySelector<HTMLElement>(".meetingPage>header"));find();const observer=new MutationObserver(find);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{void createClient().from("workspace_profiles").select("full_name").eq("workspace_id",workspaceId).eq("id",meId).maybeSingle().then(({data})=>data?.full_name&&setName(data.full_name))},[meId,workspaceId]);
 const send=async(event:FormEvent)=>{event.preventDefault();const start=new Date(starts);if(!title.trim()||Number.isNaN(start.getTime()))return setStatus("Add a valid meeting title and time.");if(start.getTime()<=Date.now())return setStatus("Meeting time must be in the future.");setBusy(true);setStatus("");const client=createClient(),{data:group,error:groupError}=await client.from("channels").select("id").eq("workspace_id",workspaceId).eq("is_workspace_group",true).maybeSingle();if(groupError||!group){setBusy(false);setStatus("Main workspace group could not be found.");return}const cleanTitle=title.trim().replace(/\s*\n\s*/g," "),cleanDetails=details.trim(),body=["📣 MEETING REMINDER",cleanTitle,start.toISOString(),String(duration),name,cleanDetails].join("\n"),{error}=await client.from("channel_messages").insert({workspace_id:workspaceId,channel_id:group.id,sender_id:meId,message_type:"text",body});setBusy(false);if(error){setStatus(error.message);return}setOpen(false);setDetails("");setStatus("Reminder sent ✓");window.setTimeout(()=>setStatus(""),3500)};
 if(!host)return null;
 return <>{createPortal(<div className="meetingReminderAction"><button className="toolPrimary" onClick={()=>setOpen(true)}>◷ Send reminder</button>{status&&!open&&<small>{status}</small>}</div>,host)}{open&&createPortal(<div className="meetingReminderBackdrop" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><form onSubmit={send}><header><span><small>MEETING REMINDER</small><h2>Schedule the conversation</h2></span><button type="button" onClick={()=>setOpen(false)}>×</button></header><label>Meeting title<input autoFocus value={title} maxLength={120} onChange={event=>setTitle(event.target.value)} placeholder="Weekly product sync"/></label><label>Date &amp; time<input type="datetime-local" value={starts} min={localDateTime(1)} onChange={event=>setStarts(event.target.value)}/></label><label>Duration<select value={duration} onChange={event=>setDuration(Number(event.target.value))}>{[15,30,45,60,90,120,180].map(value=><option value={value} key={value}>{value<60?`${value} minutes`:`${value/60} ${value===60?"hour":"hours"}`}</option>)}</select></label><label>Agenda and details<textarea value={details} maxLength={800} onChange={event=>setDetails(event.target.value)} placeholder="Topics, preparation notes, or anything members should know…"/></label>{status&&<p role="alert">{status}</p>}<footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="toolPrimary" disabled={busy}>{busy?"Sending…":"Send to main group"}</button></footer></form></div>,document.body)}</>;
}
