"use client";
import {PointerEvent as PE,ReactNode,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import "./photo-preview.css";

export default function PhotoPreview({src,name,onClose,actions}:{src:string|null;name:string;onClose:()=>void;actions?:ReactNode}) {
 const root=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null),stage=useRef<HTMLDivElement>(null),img=useRef<HTMLImageElement>(null),onCloseRef=useRef(onClose);onCloseRef.current=onClose;
 const [mobile,setMobile]=useState(false),[zoom,setZoom]=useState({scale:1,x:0,y:0});const current=useRef(zoom);current.current=zoom;
 const points=useRef(new Map<number,{x:number;y:number}>()),base=useRef({scale:1,x:0,y:0,cx:0,cy:0,distance:0}),tap=useRef(0),moved=useRef(false);
 const reset=()=>setZoom({scale:1,x:0,y:0});
 useEffect(()=>{const media=matchMedia("(max-width:760px)");const change=()=>{setMobile(media.matches);reset()};change();media.addEventListener("change",change);return()=>media.removeEventListener("change",change)},[]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onCloseRef.current();if(e.key==="Tab"){const buttons=[...(root.current?.querySelectorAll<HTMLElement>("button:not(:disabled),a,input")||[])].filter(el=>el.getClientRects().length);const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",key);previous?.focus()}},[]);
 const gesture=()=>{const p=[...points.current.values()];base.current={...current.current,cx:p.reduce((a,v)=>a+v.x,0)/p.length,cy:p.reduce((a,v)=>a+v.y,0)/p.length,distance:p.length>1?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}};
 const limit=(scale:number,x:number,y:number)=>{const mx=Math.max(0,((img.current?.offsetWidth||0)*scale-(stage.current?.clientWidth||0))/2),my=Math.max(0,((img.current?.offsetHeight||0)*scale-(stage.current?.clientHeight||0))/2);return {scale,x:Math.max(-mx,Math.min(mx,x)),y:Math.max(-my,Math.min(my,y))}};
 const down=(e:PE<HTMLDivElement>)=>{if(!mobile||!src)return;e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});moved.current=points.current.size>1;gesture()};
 const move=(e:PE<HTMLDivElement>)=>{if(!points.current.has(e.pointerId))return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=[...points.current.values()],b=base.current,cx=p.reduce((a,v)=>a+v.x,0)/p.length,cy=p.reduce((a,v)=>a+v.y,0)/p.length;if(Math.hypot(cx-b.cx,cy-b.cy)>8)moved.current=true;if(p.length>1){const scale=Math.max(1,Math.min(4,b.scale*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/(b.distance||1)));setZoom(limit(scale,b.x+cx-b.cx,b.y+cy-b.cy))}else if(b.scale>1)setZoom(limit(b.scale,b.x+cx-b.cx,b.y+cy-b.cy))};
 const up=(e:PE<HTMLDivElement>)=>{if(!points.current.has(e.pointerId))return;if(points.current.size===1){if(!moved.current&&e.pointerType==="touch"){const now=Date.now();if(now-tap.current<320){setZoom(v=>v.scale>1?{scale:1,x:0,y:0}:{scale:2.5,x:0,y:0});tap.current=0}else tap.current=now}else if(base.current.scale===1&&e.clientY-base.current.cy>120)onCloseRef.current()}points.current.delete(e.pointerId);if(points.current.size)gesture()};
 return createPortal(<div ref={root} className={`chatPhotoBackdrop photoViewer ${mobile?"mobilePhotoViewer":""}`} role="dialog" aria-modal="true" aria-label={`${name} profile photo`} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section><header className="photoViewerHeader"><button ref={close} className="photoClose" aria-label="Close photo" onClick={onClose}>{mobile?"←":"×"}</button><span>{name}</span>{mobile&&src&&<button className="photoZoom" aria-label={zoom.scale>1?"Reset zoom":"Zoom in"} onClick={()=>zoom.scale>1?reset():setZoom({scale:2.5,x:0,y:0})}>{zoom.scale>1?"−":"+"}</button>}</header><div ref={stage} className="photoViewerStage" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={e=>{points.current.delete(e.pointerId);if(points.current.size)gesture()}}>{src?<img ref={img} draggable={false} src={src} alt={`${name} profile photo`} style={mobile?{transform:`translate(${zoom.x}px,${zoom.y}px) scale(${zoom.scale})`}:undefined}/>:<div className="chatPhotoInitial">{name.slice(0,1).toUpperCase()}</div>}</div><p className="photoViewerCaption">{name}</p>{mobile&&src&&<small className="photoGestureHint">Pinch or double-tap to zoom · Swipe down to close</small>}{actions&&<div className="photoViewerActions">{actions}</div>}</section></div>,document.body);
}
