"use client";
import Link from "next/link";
import {CSSProperties,useCallback,useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {createClient} from "../../lib/supabase/client";
import {useSearchParams} from "next/navigation";
import WorkspaceCalendar from "./WorkspaceCalendar";
import WorkspaceScreenShare from "./WorkspaceScreenShare";
import WorkspaceThemePicker from "./WorkspaceThemePicker";
import WorkspaceAI from "./WorkspaceAI";
import "./workspace-tools.css";

type View="home"|"files"|"calendar"|"screen"|"ai";type Space={id:string;name:string;avatar:string|null};
const initials=(name:string)=>(name.split(" ").map(part=>part[0]).join("").slice(0,2)||"W").toUpperCase();
const currentView=():View=>{if(typeof location==="undefined")return "home";const value=new URLSearchParams(location.search).get("view");return value==="files"||value==="calendar"||value==="screen"||value==="ai"?value:"home"};
export default function WorkspaceEnhancements({workspaceId}:{workspaceId:string}){
 const searchParams=useSearchParams();
 const [view,setView]=useState<View>(currentView),[me,setMe]=useState<{id:string;name:string}|null>(null),[drawer,setDrawer]=useState(false),[spaces,setSpaces]=useState<Space[]>([]),[anchor,setAnchor]=useState<DOMRect|null>(null);
 useEffect(()=>{const value=searchParams.get("view");setView(value==="files"||value==="calendar"||value==="screen"||value==="ai"?value:"home")},[searchParams]);
 const loadSpaces=useCallback(async()=>{const client=createClient();const{data:{user}}=await client.auth.getUser();if(!user)return;const{data:profile}=await client.from("workspace_profiles").select("full_name").eq("workspace_id",workspaceId).eq("id",user.id).maybeSingle();setMe({id:user.id,name:profile?.full_name||user.email?.split("@")[0]||"Member"});const{data:memberships}=await client.from("workspace_members").select("workspace_id").eq("user_id",user.id);const ids=[...new Set([workspaceId,...(memberships||[]).map(item=>item.workspace_id)])];const[{data:workspaces},{data:groups}]=await Promise.all([client.from("workspaces").select("id,name").in("id",ids),client.from("channels").select("workspace_id,avatar_url").in("workspace_id",ids).eq("is_workspace_group",true)]);const photos=new Map((groups||[]).map(group=>[group.workspace_id,group.avatar_url]));setSpaces((workspaces||[]).map(space=>({id:space.id,name:space.name,avatar:photos.get(space.id)||null})))},[workspaceId]);
 useEffect(()=>{const timer=window.setTimeout(()=>void loadSpaces(),0),client=createClient(),channel=client.channel(`workspace-switcher:${workspaceId}`).on("postgres_changes",{event:"*",schema:"public",table:"channels"},()=>void loadSpaces()).on("postgres_changes",{event:"*",schema:"public",table:"workspaces"},()=>void loadSpaces()).on("postgres_changes",{event:"*",schema:"public",table:"workspace_members"},()=>void loadSpaces()).subscribe();return()=>{window.clearTimeout(timer);void client.removeChannel(channel)}},[loadSpaces,workspaceId]);
 useEffect(()=>{const click=(event:MouseEvent)=>{const target=event.target as HTMLElement;const picker=target.closest<HTMLButtonElement>(".spacePicker");if(picker){event.preventDefault();setAnchor(picker.getBoundingClientRect());setDrawer(value=>!value);return}const button=target.closest<HTMLButtonElement>(".proSidebar nav button");const label=button?.querySelector("span")?.textContent?.trim();if(label==="Files"){event.preventDefault();location.assign(`/workspace/${workspaceId}/files`);return}const next:View|null=label==="Home"?"home":label==="Calendar"?"calendar":label==="Meeting"?"screen":label==="Converge AI"?"ai":null;if(next){event.preventDefault();const url=new URL(location.href);if(next==="home")url.searchParams.delete("view");else url.searchParams.set("view",next);history.pushState({view:next},"",url);setView(next)}};const changed=()=>setView(currentView());document.addEventListener("click",click,true);window.addEventListener("popstate",changed);return()=>{document.removeEventListener("click",click,true);window.removeEventListener("popstate",changed)}},[workspaceId]);
 useEffect(()=>{const feed=document.querySelector<HTMLElement>(".mainFeed");feed?.scrollTo({top:0});const buttons=[...document.querySelectorAll<HTMLButtonElement>(".proSidebar nav button")];feed?.classList.toggle("workspaceToolActive",view!=="home");for(const button of buttons){const label=button.querySelector("span")?.textContent?.trim();button.classList.toggle("active",label===(view==="home"?"Home":view==="files"?"Files":view==="calendar"?"Calendar":view==="ai"?"Converge AI":"Meeting"))}return()=>feed?.classList.remove("workspaceToolActive")},[view]);
 useEffect(()=>{if(view==="files")location.replace(`/workspace/${workspaceId}/files`)},[view,workspaceId]);
 useEffect(()=>{if(!drawer)return;const close=(event:PointerEvent)=>{if((event.target as Element).closest(".spacePicker,.globalWorkspaceDrawer"))return;setDrawer(false)};const resize=()=>{const picker=document.querySelector(".spacePicker");if(picker)setAnchor(picker.getBoundingClientRect())};document.addEventListener("pointerdown",close);window.addEventListener("resize",resize);return()=>{document.removeEventListener("pointerdown",close);window.removeEventListener("resize",resize)}},[drawer]);
 if(typeof document==="undefined")return null;const feed=document.querySelector(".mainFeed"),nav=document.querySelector(".proSidebar nav");const style=anchor?{top:anchor.bottom+8,left:anchor.left,width:Math.max(anchor.width,230)} as CSSProperties:undefined;
 const hasScreenButton=nav?[...nav.querySelectorAll("button")].some(button=>button.querySelector("span")?.textContent?.trim()==="Meeting"):false;
 return <>{me&&<WorkspaceThemePicker workspaceId={workspaceId} userId={me.id}/>} {nav&&!hasScreenButton&&createPortal(<button data-screen-share className={view==="screen"?"active":""}><svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4m0-13v6m-3-3 3 3 3-3"/></svg><span>Meeting</span></button>,nav)}{feed&&view!=="home"&&createPortal(<div className="workspaceToolHost">{view==="calendar"&&<WorkspaceCalendar workspaceId={workspaceId}/>} {view==="screen"&&me&&<WorkspaceScreenShare workspaceId={workspaceId} meId={me.id} myName={me.name}/>} {view==="ai"&&me&&<WorkspaceAI workspaceId={workspaceId} meId={me.id} myName={me.name}/>}</div>,feed)}{drawer&&createPortal(<aside className="workspaceDrawer globalWorkspaceDrawer" style={style} role="menu"><header><small>YOUR WORKSPACES</small><b>Switch workspace</b></header><div>{spaces.map(space=><Link role="menuitem" className={space.id===workspaceId?"active":""} href={`/workspace/${space.id}`} key={space.id}><i>{space.avatar?<img src={space.avatar} alt=""/>:initials(space.name)}</i><span><b>{space.name}</b><small>{space.id===workspaceId?"Current workspace":"Open home"}</small></span>{space.id===workspaceId&&<em>✓</em>}</Link>)}</div><Link className="allSpaces" href="/dashboard">View all workspaces →</Link></aside>,document.body)}</>;
}
