"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase/client";
import "./workspace-tools.css";
type EventItem={id:string;title:string;date:string;time:string;visibility:"private"|"workspace";creator_id?:string};
const storageKey=(workspaceId:string)=>`converge:calendar:${workspaceId}`;
export default function WorkspaceCalendar({workspaceId}:{workspaceId:string}){
 const [cursor,setCursor]=useState(()=>new Date()),[events,setEvents]=useState<EventItem[]>([]),[meId,setMeId]=useState(""),[dialog,setDialog]=useState(false),[title,setTitle]=useState(""),[date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[time,setTime]=useState("09:00"),[visibility,setVisibility]=useState<"private"|"workspace">("private"),[status,setStatus]=useState("");
 const load=useCallback(async()=>{const client=createClient(),{data:{user}}=await client.auth.getUser();if(!user)return;setMeId(user.id);const{data,error}=await client.from("workspace_events").select("id,title,starts_at,visibility,creator_id").eq("workspace_id",workspaceId).order("starts_at");if(!error&&data){setEvents(data.map(item=>{const value=new Date(item.starts_at),local=new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString();return{id:item.id,title:item.title,date:local.slice(0,10),time:local.slice(11,16),visibility:item.visibility,creator_id:item.creator_id}}));return}try{setEvents(JSON.parse(localStorage.getItem(storageKey(workspaceId))||"[]"))}catch{setEvents([])}},[workspaceId]);
 useEffect(()=>{const first=window.setTimeout(()=>void load(),0),client=createClient(),sync=()=>void load(),channel=client.channel(`workspace-calendar:${workspaceId}`).on("postgres_changes",{event:"*",schema:"public",table:"workspace_events",filter:`workspace_id=eq.${workspaceId}`},sync).subscribe(),fallback=window.setInterval(()=>{if(document.visibilityState==="visible")sync()},5000);window.addEventListener("focus",sync);return()=>{window.clearTimeout(first);window.clearInterval(fallback);window.removeEventListener("focus",sync);void client.removeChannel(channel)}},[load,workspaceId]);
 const year=cursor.getFullYear(),month=cursor.getMonth(),days=new Date(year,month+1,0).getDate(),offset=(new Date(year,month,1).getDay()+6)%7,cells=Array.from({length:offset+days},(_,i)=>i<offset?null:i-offset+1),today=new Date().toDateString(),upcoming=useMemo(()=>events.filter(item=>new Date(`${item.date}T${item.time}`)>=new Date()).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).slice(0,7),[events]);
 const save=async(event:FormEvent)=>{event.preventDefault();if(!title.trim()||!meId)return;setStatus("Saving event…");const c=createClient(),startsAt=new Date(`${date}T${time}`).toISOString(),draft={id:crypto.randomUUID(),title:title.trim(),date,time,visibility,creator_id:meId} satisfies EventItem,{data,error}=await c.from("workspace_events").insert({workspace_id:workspaceId,creator_id:meId,title:draft.title,starts_at:startsAt,visibility}).select("id").single(),saved={...draft,id:data?.id||draft.id};setEvents(current=>[...current,saved]);if(error)localStorage.setItem(storageKey(workspaceId),JSON.stringify([...events,saved]));if(visibility==="workspace"){const{data:group}=await c.from("channels").select("id").eq("workspace_id",workspaceId).eq("is_workspace_group",true).maybeSingle();if(group)await c.from("channel_messages").insert({workspace_id:workspaceId,channel_id:group.id,sender_id:meId,message_type:"event",body:`📅 ${draft.title}\n${new Date(startsAt).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}\nWorkspace event`})}setTitle("");setDialog(false);setStatus(error?"Saved locally. Run workspace-calendar-events-migration.sql once for team sync.":"Event saved and shared.")};
 return <section className="workspaceToolPage calendarPage"><header><div><small>TEAM SCHEDULE</small><h1>Calendar</h1><p>Private reminders stay with you. Workspace events appear for everyone and are announced in the main group.</p>{status&&<em className="calendarStatus">{status}</em>}</div><button className="toolPrimary" onClick={()=>setDialog(true)}>＋ New event</button></header><div className="calendarLayout"><section className="monthCard"><header><button onClick={()=>setCursor(new Date(year,month-1,1))}>‹</button><h2>{cursor.toLocaleDateString([],{month:"long",year:"numeric"})}</h2><button onClick={()=>setCursor(new Date(year,month+1,1))}>›</button></header><div className="weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><b key={day}>{day}</b>)}</div><div className="monthGrid">{cells.map((day,index)=>day?<button key={day} className={new Date(year,month,day).toDateString()===today?"today":""}><span>{day}</span>{events.filter(item=>item.date===`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`).slice(0,2).map(item=><i className={item.visibility} key={item.id}>{item.title}</i>)}</button>:<span key={`blank-${index}`}/>)}</div></section><aside className="upcomingCard"><small>UP NEXT</small><h2>Upcoming</h2>{upcoming.length?upcoming.map(item=><article key={item.id}><time>{new Date(`${item.date}T${item.time}`).toLocaleDateString([],{day:"2-digit",month:"short"})}</time><span><b>{item.title}</b><small>{item.time} · {item.visibility==="workspace"?"Everyone":"Only me"}</small></span></article>):<p>No upcoming events yet.</p>}</aside></div>{dialog&&<div className="toolDialog" onMouseDown={event=>event.target===event.currentTarget&&setDialog(false)}><form onSubmit={save}><header><span><small>NEW EVENT</small><h2>Add to calendar</h2></span><button type="button" onClick={()=>setDialog(false)}>×</button></header><label>Event title<input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder="Weekly design review"/></label><div><label>Date<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Time<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><fieldset className="eventAudience"><legend>Who should see it?</legend><button type="button" className={visibility==="private"?"active":""} onClick={()=>setVisibility("private")}><b>Only me</b><small>Private reminder</small></button><button type="button" className={visibility==="workspace"?"active":""} onClick={()=>setVisibility("workspace")}><b>Everyone</b><small>Calendar + group chat</small></button></fieldset><button className="toolPrimary">Save event</button></form></div>}</section>;
}
