"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase/client";
import ChatMediaViewer,{type ChatMediaItem} from "./ChatMediaViewer";
import "./workspace-tools.css";

type Asset={id:string;conversationId:string;kind:"media"|"file"|"link";name:string;url:string;sender:string;created_at:string;video:boolean};
type Conversation={id:string;name:string;avatar:string|null;group:boolean};
const urls=(text:string)=>(text.match(/https?:\/\/[^\s<]+/g)||[]).map(url=>url.replace(/[),.!?]+$/,""));
const initials=(name:string)=>(name.split(" ").map(part=>part[0]).join("").slice(0,2)||"C").toUpperCase();
export default function WorkspaceFiles({workspaceId,meId}:{workspaceId:string;meId:string}){
 const [assets,setAssets]=useState<Asset[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState(""),[tab,setTab]=useState<"media"|"file"|"link">("media"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[viewer,setViewer]=useState<string|null>(null);
 useEffect(()=>{let alive=true;void(async()=>{const client=createClient();const[{data:channels},{data:groupMessages},{data:directMessages},{data:people}]=await Promise.all([client.from("channels").select("id,name,avatar_url").eq("workspace_id",workspaceId).eq("kind","group"),client.from("channel_messages").select("id,channel_id,sender_id,body,message_type,attachment_url,attachment_name,created_at").eq("workspace_id",workspaceId).neq("message_type","system"),client.from("direct_messages").select("id,sender_id,recipient_id,body,message_type,attachment_url,attachment_name,created_at").eq("workspace_id",workspaceId).or(`sender_id.eq.${meId},recipient_id.eq.${meId}`),client.from("workspace_profiles").select("id,full_name,avatar_url").eq("workspace_id",workspaceId)]);if(!alive)return;const names=new Map((people||[]).map(person=>[person.id,person.full_name||"Member"])),profiles=new Map((people||[]).map(person=>[person.id,person]));const nextConversations:Conversation[]=(channels||[]).map(channel=>({id:`group:${channel.id}`,name:channel.name,avatar:channel.avatar_url||null,group:true}));const directIds=[...new Set((directMessages||[]).map(row=>row.sender_id===meId?row.recipient_id:row.sender_id))];for(const id of directIds){const person=profiles.get(id);nextConversations.push({id:`direct:${id}`,name:person?.full_name||"Member",avatar:person?.avatar_url||null,group:false})}const next:Asset[]=[];const add=(row:{id:string;sender_id:string;body?:string|null;message_type?:string;attachment_url?:string|null;attachment_name?:string|null;created_at:string},conversationId:string)=>{if(row.attachment_url){const media=row.message_type==="media";next.push({id:row.id,conversationId,kind:media?"media":"file",name:row.attachment_name||"Shared attachment",url:row.attachment_url,sender:names.get(row.sender_id)||"Member",created_at:row.created_at,video:media&&/\.(mp4|webm|mov|ogg)(?:$|\?)/i.test(row.attachment_name||row.attachment_url)})}for(const [index,url] of urls(row.body||"").entries())next.push({id:`${row.id}-link-${index}`,conversationId,kind:"link",name:url,url,sender:names.get(row.sender_id)||"Member",created_at:row.created_at,video:false})};for(const row of groupMessages||[])add(row,`group:${row.channel_id}`);for(const row of directMessages||[]){const other=row.sender_id===meId?row.recipient_id:row.sender_id;add(row,`direct:${other}`)}setConversations(nextConversations);setSelected(current=>current||nextConversations[0]?.id||"");setAssets(next.sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at)));setLoading(false)})().catch(reason=>{if(alive){setError(reason instanceof Error?reason.message:"Files could not load.");setLoading(false)}});return()=>{alive=false}},[meId,workspaceId]);
 const conversation=conversations.find(item=>item.id===selected),counts=(id:string)=>assets.filter(item=>item.conversationId===id).length;const shown=assets.filter(item=>item.conversationId===selected&&item.kind===tab&&item.name.toLowerCase().includes(query.toLowerCase()));const media=useMemo(()=>shown.filter(item=>item.kind==="media").map(item=>({id:item.id,url:item.url,name:item.name,video:item.video} satisfies ChatMediaItem)),[shown]),index=viewer?media.findIndex(item=>item.id===viewer):-1;
 return <section className="workspaceLibrary"><aside className="libraryChats"><header><small>SHARED CONTENT</small><h1>Files</h1></header><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search in conversation"/></label><div>{conversations.map(item=><button className={selected===item.id?"active":""} key={item.id} onClick={()=>setSelected(item.id)}><i>{item.avatar?<img src={item.avatar} alt=""/>:item.group?"♧":initials(item.name)}</i><span><b>{item.name}</b><small>{counts(item.id)} shared items</small></span><em>›</em></button>)}</div></aside><section className="libraryDetail"><header><div><small>{conversation?.group?"GROUP":"PERSONAL CHAT"}</small><h2>{conversation?.name||"Choose a conversation"}</h2><p>Media, documents and links shared in this conversation.</p></div></header>{conversation&&<nav>{(["media","file","link"] as const).map(value=><button className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value==="file"?"Documents":value[0].toUpperCase()+value.slice(1)} <span>{assets.filter(item=>item.conversationId===selected&&item.kind===value).length}</span></button>)}</nav>}{loading?<div className="toolEmpty">Loading conversations…</div>:error?<div className="toolEmpty error">{error}</div>:shown.length?<div className="libraryItems">{shown.map(item=>item.kind==="media"?<button className="libraryItem media" key={item.id} onClick={()=>setViewer(item.id)}>{item.video?<video src={item.url} muted preload="metadata"/>:<img src={item.url} alt="" loading="lazy"/>}<span><b>{item.name}</b><small>Sent by {item.sender}</small><time>{new Date(item.created_at).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</time></span></button>:<a className={`libraryItem ${item.kind}`} key={item.id} href={item.url} target="_blank" rel="noreferrer"><i>{item.kind==="link"?"↗":"▧"}</i><span><b>{item.name}</b><small>Sent by {item.sender}</small><time>{new Date(item.created_at).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</time></span></a>)}</div>:<div className="toolEmpty"><i>◇</i><h2>No {tab==="file"?"documents":tab} here</h2><p>Anything shared in this conversation will appear with its sender and time.</p></div>}{index>=0&&<ChatMediaViewer items={media} index={index} onChange={next=>setViewer(media[next]?.id||null)} onClose={()=>setViewer(null)}/>}</section></section>;
}
