"use client";

import { useEffect, useRef, useState } from "react";
import {createPortal} from "react-dom";
import { usePathname, useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import { startRingtone } from "./ringtone";
import "./workspace-realtime-hub.css";

type MessageToast={id:string;workspaceId:string;chatId:string;channelId?:string;senderId:string;name:string;avatar:string|null;body:string;group:boolean};
type IncomingCall={workspaceId:string;callerId:string;name:string;avatar:string|null;mode:"audio"|"video";group:boolean;channelId?:string;callId?:string;groupName?:string};
const safely=(promise:Promise<unknown>)=>{void promise.catch(()=>{})};

const notificationSound=()=>{
 try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.setValueAtTime(740,context.currentTime);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.12,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.32);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.34)}catch{}
};

export default function WorkspaceRealtimeHub({workspaceId}:{workspaceId:string}){
 const pathname=usePathname();const router=useRouter();const [meId,setMeId]=useState("");const [toast,setToast]=useState<MessageToast|null>(null);const [replying,setReplying]=useState(false);const [replyText,setReplyText]=useState("");const [replyBusy,setReplyBusy]=useState(false);const [replyError,setReplyError]=useState("");const [call,setCall]=useState<IncomingCall|null>(null);const seen=useRef(new Set<string>());const toastTimer=useRef<number|null>(null);const stopRing=useRef<(()=>void)|null>(null);const callKey=useRef("");const pathRef=useRef(pathname);
 useEffect(()=>{pathRef.current=pathname},[pathname]);
 useEffect(()=>{safely(createClient().auth.getUser().then(({data})=>setMeId(data.user?.id||"")))},[]);
 useEffect(()=>{if(!meId)return;const client=createClient();const load=async()=>{const{data}=await client.rpc("get_workspace_unread_chats",{target_workspace_id:workspaceId});const count=(data||[]).length;for(const button of document.querySelectorAll<HTMLButtonElement>(".proSidebar nav button")){if(button.querySelector("span")?.textContent?.trim()!=="Messages")continue;if(count)button.dataset.unreadChats=count>99?"99+":String(count);else delete button.dataset.unreadChats}};let last=0,busy=false;const changed=()=>{if(busy||Date.now()-last<1500)return;busy=true;last=Date.now();safely(load().finally(()=>{busy=false}))};changed();window.addEventListener("converge:unread-chats",changed);const channel=client.channel(`global-unread:${workspaceId}:${meId}`).on("postgres_changes",{event:"*",schema:"public",table:"direct_message_receipts",filter:`workspace_id=eq.${workspaceId}`},changed).on("postgres_changes",{event:"*",schema:"public",table:"channel_message_receipts",filter:`workspace_id=eq.${workspaceId}`},changed).subscribe();const fallback=window.setInterval(changed,15000);return()=>{window.clearInterval(fallback);window.removeEventListener("converge:unread-chats",changed);void client.removeChannel(channel)}},[meId,pathname,workspaceId]);
 useEffect(()=>{if(!toast||replying)return;if(toastTimer.current)window.clearTimeout(toastTimer.current);toastTimer.current=window.setTimeout(()=>setToast(null),7000);return()=>{if(toastTimer.current)window.clearTimeout(toastTimer.current)}},[toast,replying]);
 useEffect(()=>()=>{stopRing.current?.()},[]);
 useEffect(()=>{
  if(!meId)return;let active=true;const client=createClient();
  const profile=async(id:string)=>{const{data}=await client.from("workspace_profiles").select("full_name,avatar_url").eq("workspace_id",workspaceId).eq("id",id).maybeSingle();return {name:data?.full_name||"Workspace member",avatar:data?.avatar_url||null}};
  const showMessage=async(row:{id:string;workspace_id?:string;sender_id:string;recipient_id?:string;channel_id?:string;body?:string;attachment_name?:string;message_type?:string},group:boolean,announce=true)=>{if(!active||row.workspace_id!==workspaceId||row.message_type==="system"||row.sender_id===meId||seen.current.has(row.id))return;seen.current.add(row.id);const chatId=group?"group":row.sender_id;if(!group&&localStorage.getItem(`converge:direct-muted:${workspaceId}:${meId}:${chatId}`)==="1")return;window.dispatchEvent(new CustomEvent("converge:unread-chats"));if(pathRef.current.endsWith(`/messages/${chatId}`))return;const sender=await profile(row.sender_id);if(!active)return;setReplying(false);setReplyText("");setReplyError("");setToast({id:row.id,workspaceId,chatId,channelId:row.channel_id,senderId:row.sender_id,name:sender.name,avatar:sender.avatar,body:row.message_type==="voice"?"Voice message":row.body||row.attachment_name||"Sent an attachment",group});if(announce)notificationSound()};
  const initialize=async()=>{const since=new Date(Date.now()-3000).toISOString();const[{data:direct},{data:group}]=await Promise.all([client.from("direct_messages").select("id,workspace_id,sender_id,recipient_id,body,attachment_name,message_type,created_at").eq("workspace_id",workspaceId).eq("recipient_id",meId).gte("created_at",since),client.from("channel_messages").select("id,workspace_id,sender_id,channel_id,body,attachment_name,created_at,message_type").eq("workspace_id",workspaceId).neq("message_type","system").gte("created_at",since)]);for(const row of direct||[])void showMessage(row,false,false);for(const row of group||[])void showMessage(row,true,false)};
  safely(initialize());
  const messageChannel=client.channel(`workspace-message-hub:${workspaceId}:${meId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"direct_messages",filter:`recipient_id=eq.${meId}`},({new:row})=>safely(showMessage(row as Parameters<typeof showMessage>[0],false))).on("postgres_changes",{event:"INSERT",schema:"public",table:"channel_messages",filter:`workspace_id=eq.${workspaceId}`},({new:row})=>safely(showMessage(row as Parameters<typeof showMessage>[0],true))).subscribe();
  const poll=window.setInterval(()=>safely((async()=>{const since=new Date(Date.now()-30000).toISOString();const[{data:direct},{data:group}]=await Promise.all([client.from("direct_messages").select("id,workspace_id,sender_id,recipient_id,body,attachment_name,message_type").eq("workspace_id",workspaceId).eq("recipient_id",meId).gte("created_at",since),client.from("channel_messages").select("id,workspace_id,sender_id,channel_id,body,attachment_name,message_type").eq("workspace_id",workspaceId).neq("message_type","system").gte("created_at",since)]);for(const row of direct||[])await showMessage(row,false);for(const row of group||[])await showMessage(row,true)})()),10000);
  return()=>{active=false;window.clearInterval(poll);void client.removeChannel(messageChannel)}
 },[meId,workspaceId]);
 useEffect(()=>{
  if(!meId)return;let active=true;const client=createClient();
  const showCall=async(callerId:string,mode:"audio"|"video",group=false,name?:string,sourceWorkspaceId=workspaceId,channelId?:string,callId?:string,groupName?:string)=>{if(!active||sourceWorkspaceId!==workspaceId||callerId===meId)return;if(group){if(!channelId||!callId)return;const[{data:channel},{data:membership}]=await Promise.all([client.from("channels").select("id,is_workspace_group").eq("workspace_id",workspaceId).eq("id",channelId).maybeSingle(),client.from("channel_members").select("user_id,left_at").eq("channel_id",channelId).eq("user_id",meId).maybeSingle()]);if(!channel||(!channel.is_workspace_group&&(!membership||membership.left_at)))return;const currentChannel=new URLSearchParams(window.location.search).get("channel");if(pathRef.current.endsWith("/messages/group")&&currentChannel===channelId)return}else{const{data:blocked}=await client.rpc("direct_chat_is_blocked",{target_workspace_id:workspaceId,target_partner_id:callerId});if(blocked===true||pathRef.current.endsWith(`/messages/${callerId}`))return}const nextKey=`${workspaceId}:${group?channelId||"group":"direct"}:${callId||callerId}:${mode}`;if(callKey.current===nextKey)return;callKey.current=nextKey;const {data:person}=await client.from("workspace_profiles").select("full_name,avatar_url").eq("workspace_id",workspaceId).eq("id",callerId).maybeSingle();if(!active)return;const callerName=name||person?.full_name||"Workspace member";setCall({workspaceId,callerId,name:callerName,avatar:person?.avatar_url||null,mode,group,channelId,callId,groupName});stopRing.current?.();stopRing.current=startRingtone()};
  const direct=client.channel(`global-call-hub:${workspaceId}:${meId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"call_signals",filter:`recipient_id=eq.${meId}`},({new:row})=>{const signal=row as {workspace_id:string;sender_id:string;signal_type:string;mode:"audio"|"video"|null};if(signal.signal_type==="offer")safely(showCall(signal.sender_id,signal.mode||"audio",false,undefined,signal.workspace_id))}).subscribe();
  const group=client.channel(`group-call:${workspaceId}`,{config:{private:true}}).on("broadcast",{event:"signal"},({payload})=>{const signal=payload as {type:string;from:string;workspaceId?:string;channelId?:string;callId?:string;mode?:"audio"|"video";name?:string;groupName?:string};if(signal.type==="ring")safely(showCall(signal.from,signal.mode||"audio",true,signal.name,signal.workspaceId,signal.channelId,signal.callId,signal.groupName))}).subscribe();
  const poll=window.setInterval(()=>safely((async()=>{const{data}=await client.from("call_signals").select("sender_id,mode").eq("workspace_id",workspaceId).eq("recipient_id",meId).eq("signal_type","offer").order("created_at",{ascending:false}).limit(1);if(data?.[0])await showCall(data[0].sender_id,(data[0].mode||"audio") as "audio"|"video")})()),5000);
  return()=>{active=false;window.clearInterval(poll);void client.removeChannel(direct);void client.removeChannel(group)}
 },[meId,workspaceId]);
 const openChat=(item:MessageToast)=>{setToast(null);if(item.workspaceId!==workspaceId)return;router.push(`/workspace/${workspaceId}/messages/${item.chatId}`)};
 const beginReply=()=>{if(toastTimer.current)window.clearTimeout(toastTimer.current);setReplying(true);setReplyError("");requestAnimationFrame(()=>document.querySelector<HTMLInputElement>(".toastReplyForm input")?.focus())};
 const sendToastReply=async(event:React.FormEvent)=>{event.preventDefault();if(!toast||toast.workspaceId!==workspaceId||!meId||!replyText.trim()||replyBusy)return;setReplyBusy(true);setReplyError("");const client=createClient();const payload={workspace_id:workspaceId,sender_id:meId,body:replyText.trim(),message_type:"text",attachment_url:null,attachment_name:null,post_id:null};const result=toast.group&&toast.channelId?await client.from("channel_messages").insert({...payload,channel_id:toast.channelId}):!toast.group?await client.from("direct_messages").insert({...payload,recipient_id:toast.senderId}):{error:{message:"Group chat is not ready."}};setReplyBusy(false);if(result.error){setReplyError(result.error.message);return}setReplyText("");setReplying(false);setToast(null);window.dispatchEvent(new CustomEvent("converge:unread-chats"))};
 const markSeen=async(item:MessageToast)=>{if(item.workspaceId!==workspaceId)return;const client=createClient();if(item.group&&item.channelId)await client.rpc("mark_group_chat_read",{target_workspace_id:workspaceId,target_channel_id:item.channelId});else if(!item.group)await client.rpc("mark_direct_chat_read",{target_workspace_id:workspaceId,target_sender_id:item.senderId});setToast(null);window.dispatchEvent(new CustomEvent("converge:unread-chats"))};
 const answerCall=(item:IncomingCall)=>{if(item.workspaceId!==workspaceId||item.group&&(!item.channelId||!item.callId))return;stopRing.current?.();stopRing.current=null;callKey.current="";const key=item.group?`converge:auto-answer:${workspaceId}:group:${item.channelId}`:`converge:auto-answer:${workspaceId}:${item.callerId}`;sessionStorage.setItem(key,JSON.stringify({callerId:item.callerId,mode:item.mode,channelId:item.channelId,callId:item.callId,groupName:item.groupName}));setCall(null);router.push(item.group?`/workspace/${workspaceId}/messages/group?channel=${item.channelId}`:`/workspace/${workspaceId}/messages/${item.callerId}`)};
 const rejectCall=async(item:IncomingCall)=>{if(item.workspaceId!==workspaceId)return;stopRing.current?.();stopRing.current=null;callKey.current="";setCall(null);if(!item.group){const client=createClient();await client.from("call_signals").insert({workspace_id:workspaceId,sender_id:meId,recipient_id:item.callerId,signal_type:"hangup",mode:item.mode,signal:{__callEnvelope:1,reason:"Declined"}});await client.from("call_signals").delete().eq("workspace_id",workspaceId).eq("recipient_id",meId).eq("sender_id",item.callerId).eq("signal_type","offer")}};
 if(typeof document==="undefined")return null;
 return createPortal(<>
  {toast&&toast.workspaceId===workspaceId&&<aside className={`workspaceMessageToast ${replying?"replying":""}`}>
   <button className="toastBody" onClick={()=>openChat(toast)}><i>{toast.avatar?<img src={toast.avatar} alt=""/>:toast.name.slice(0,1).toUpperCase()}</i><span><b>{toast.group?`${toast.name} · Group`:toast.name}</b><small>{toast.body}</small></span></button>
   {replying?<form className="toastReplyForm" onSubmit={event=>void sendToastReply(event)}><input value={replyText} onChange={event=>setReplyText(event.target.value)} placeholder={`Reply to ${toast.name}…`} aria-label="Notification reply"/><button disabled={!replyText.trim()||replyBusy}>{replyBusy?"…":"Send"}</button><button type="button" className="toastReplyClose" aria-label="Cancel reply" onClick={()=>{setReplying(false);setReplyText("");setReplyError("")}}>×</button>{replyError&&<small role="alert">{replyError}</small>}</form>:<footer><button onClick={beginReply}>Reply</button><button onClick={()=>void markSeen(toast)}>Seen</button></footer>}
   {!replying&&<em/>}
  </aside>}
  {call&&<div className="globalIncomingCall"><section><i className="incomingCallerPhoto">{call.avatar?<img src={call.avatar} alt={call.name}/>:call.name.slice(0,1).toUpperCase()}</i><small>INCOMING {call.group?"GROUP ":""}{call.mode.toUpperCase()} CALL</small><h2>{call.group&&call.groupName?call.groupName:call.name}</h2>{call.group&&<p>{call.name} started the call</p>}<div><button onClick={()=>answerCall(call)}>Answer</button><button onClick={()=>void rejectCall(call)}>Reject</button></div></section></div>}
 </>,document.body);
}
