"use client";

import { useState } from "react";
import ScrollExperience from "./ScrollExperience";

function Mark() {
  return <svg className="mark" viewBox="0 0 64 58" aria-label="Converge logo"><path d="M32 29C22 11 7 11 7 24c0 11 11 15 25 5"/><path d="M32 29C52 11 59 24 54 35c-4 9-16 6-22-6"/><path d="M32 29C29 53 14 52 13 39c0-11 11-14 19-10"/><circle cx="32" cy="29" r="4"/></svg>;
}
const Arrow=()=> <span></span>;
export default function Home(){
 const [kind,setKind]=useState("Startup"); const choices={Startup:["Company updates","Product crew","Launch room"],"Student team":["Class hub","Project group","Study room"],"Creative studio":["Studio updates","Client room","Feedback group"]};
 return <main className="landingPage"><ScrollExperience/>
  <nav><a className="brand" href="#top"><Mark/>CONVERGE</a><div className="links"><a href="#story">Product</a><a href="#spaces">Workflows</a><a href="#security">Privacy</a></div><div className="navButtons"><a className="signin" href="/auth?mode=signin">Sign in</a><a className="button" href="/auth?next=/onboarding">Create workspace <Arrow/></a></div></nav>
  <section id="top" className="hero pad"><div className="copy"><p className="eyebrow">Your team&apos;s private digital workspace</p><h1>Make work<br/>feel <em>alive.</em></h1><p className="lead">Bring posts, private and group chat, calls, meetings, files, calendars and workspace-aware AI into one focused place.</p><p className="actions"><a className="button" href="/auth?next=/onboarding">Create workspace <Arrow/></a><a className="textlink" href="#story">Explore Converge</a></p></div><div className="heroArt" aria-hidden="true"><i className="orbit o1"/><i className="orbit o2"/><i className="orbit o3"/><div className="core"><b/><b/><b/><strong></strong></div><span className="floatcard c1">Team poll · 12 votes</span><span className="floatcard c2">Group call · Live</span><span className="floatcard c3">Strategy deck.pdf</span></div><div className="trusted">BUILT FOR STARTUPS, STUDENT TEAMS, AND CREATIVE GROUPS</div></section>
  <section id="story" className="noise pad"><p className="label">01 <i/></p><h2>The noise<br/>before momentum.</h2><p className="muted">Messages in one app, meetings in another, and files buried in links. Context gets lost before work begins.</p><div className="fragments"><span>12 unread messages</span><span>Campaign brief.pdf</span><span>Meeting reminder · 11:00</span><span>Voice note · 02:37</span><span>Team poll</span><span>Shared post</span><i/></div></section>
  <section className="story pad"><p className="label">02 <i/></p><div className="storyCopy"><h2>Watch your<br/>work <em>converge.</em></h2><p className="muted">A shared feed, direct and group conversations, files, events and AI—all scoped to the workspace you are in.</p></div><div className="window currentWorkspacePreview"><aside><Mark/><span>Home</span><span>Messages</span><b>Groups</b><span>Files</span><span>Calendar</span><span>Converge AI</span></aside><div className="chat previewFeed"><header><span><Mark/><b>CONVERGE</b></span><small>Search · Alerts · Create</small></header><article><div><i>M</i><span><b>Maya</b><small>Product designer · 10:41 AM</small></span></div><p>The updated launch plan is ready. Which direction should we ship?</p><section><small>POLL · SELECT ONE</small><b>Focused release <em>68%</em></b><b>Full launch <em>32%</em></b></section><footer><span>♥ 12</span><span>◯ 4</span><span>Share</span><span>Save</span></footer></article><nav><span>Home</span><span>Messages</span><b>AI</b><span>Files</span><span>Profile</span></nav></div><aside className="activity"><b>Up next</b><p>Launch review<br/><small>Tomorrow · 11:00</small></p><p>Campaign-Deck.ppt<br/><small>Shared in Files</small></p></aside></div></section>
  <section id="spaces" className="spaces pad"><p className="label">03 <i/></p><div className="spaceIntro"><div><h2>Built for the<br/>way you work.</h2><p className="muted">Create a workspace, shape your profile, and organise people into focused groups without mixing data between spaces.</p></div><div className="suggest"><small>A workspace can include</small>{choices[kind as keyof typeof choices].map(x=><b key={x}>{x}</b>)}</div></div><div className="choices">{Object.entries(choices).map(([name,ch],i)=><button onClick={()=>setKind(name)} className={kind===name?"selected":""} key={name}><small>0{i+1}</small><strong>{name}</strong><p>{name==="Startup"?"Share updates, align quickly and meet live.":name==="Student team"?"Plan, discuss, share resources and learn together.":"Keep briefs, feedback and client conversations connected."}</p>{ch.map(x=><i key={x}>{x}</i>)}</button>)}</div></section>
  <section className="flows pad"><p className="label">04 <i/></p><div className="flowIntro"><h2>One space.<br/>Every flow.</h2><p className="muted">Publish updates and polls, share posts into chat, send voice notes, call your team, schedule events and keep files discoverable.</p></div><div className="flowGrid"><div className="messages flowChatPreview"><header><i>T</i><span><b>TechTeam</b><small>8 members</small></span><em>⌕ · ⋮</em></header><section><p className="theirs"><b>Maya</b><span>The launch poll is live—please vote.</span><small>10:41 AM</small></p><p className="mine"><span>I&apos;ve shared the final launch plan.</span><small>10:43 AM ✓✓</small></p><p className="theirs"><b>Noah</b><span>Perfect. Joining the team call now.</span><small>10:44 AM</small></p></section><footer><button type="button" aria-label="Add attachment">＋</button><i aria-hidden="true">☺</i><span>Write a message…</span><button type="button" aria-label="Send message">➤</button></footer></div><div className="call"><div><i><img src="/team/jordan.png" alt="Jordan, software engineer"/></i><i><img src="/team/maya.png" alt="Maya, product designer"/></i><i><img src="/team/lena.png" alt="Lena, strategy lead"/></i><i><img src="/team/armin.png" alt="Armin, product manager"/></i></div><footer>Group voice &amp; video calls</footer></div><div className="timeline"><b>Calendar &amp; files</b><i/><i/><i/><p>Upcoming<br/><small>Launch review · 11:00</small><small>Campaign-Deck.ppt</small></p></div></div></section>
  <section className="ai pad"><p className="label">05 <i/></p><div className="aiCopy"><h2>AI that knows<br/>this workspace.</h2><p className="muted">Ask Converge AI to find relevant workspace context, summarize conversations and surface meeting details with links back to the source.</p></div><div className="orb"></div><div className="prompts"><button>Summarize our latest discussion</button><button>When is the next meeting?</button><button>Find the launch decision</button></div></section>
  <section id="security" className="security pad"><p className="label">06 <i/></p><div className="secCopy"><h2>Privacy by<br/>workspace.</h2><p className="muted">Identity, messages, calls, notifications and group membership stay scoped to the workspace where they belong.</p></div><div className="map"><b></b><span>Profiles</span><span>Messages</span><span>Calls</span><span>Files</span><span>Groups</span><span>Notifications</span></div><div className="roles"><b>Access model</b><p> Owner <i>Workspace control</i></p><p> Group admin <i>Manage group</i></p><p> Member <i>Collaborate</i></p><p> Former member <i>Read retained chat</i></p></div></section>
  <section id="create" className="closing pad"><div/><article><p className="eyebrow"> YOUR WORKSPACE IS WAITING</p><h2>Build the place<br/>your team <em>deserves.</em></h2><p className="muted">Converge brings clarity to chaos - so teams can do their best work, together.</p><a className="button" href="/auth?next=/onboarding">Get started <Arrow/></a></article></section>
  <footer><div><a className="brand" href="#top"><Mark/>CONVERGE</a><p>Where workspace conversations, content and collaboration come alive.</p><small className="authorCredit">Created by Harsh Shukla</small></div><div><b>Product</b><a href="#story">Messages &amp; groups</a><a href="#spaces">Workflows</a><a href="#security">Privacy</a></div><div><b>For teams</b><a href="#spaces">Startups</a><a href="#spaces">Student teams</a><a href="#spaces">Creative studios</a></div><div><b>Ready to converge?</b><p>Start a private workspace for your team.</p><a className="button" href="/auth?next=/onboarding">Create workspace</a></div></footer>
 </main>
}
